### ISSUE TITLE
Support for SLES and Oracle Linux

### ISSUE THREAD

**Issue by bernardoVale** [NBZ4live/ansible-nagios-nrpe-server#1]
Hello, you've wrote a pretty good module, congratulations. Unfortunetly I have a pretty heterogeneous environment so I need this also to work with OracleLinux, SLES and RedHat.

I was planning to write a role to install nrpe by myself but it will be a lot less effort to add this support on your role instead of writing from scratch.

Do you have plans to support others distributions? Can I add this pulling a request?

**Comment by NBZ4live** [comment]
I don't use this distributions.
But you can make a pull request with this support
